#!/bin/sh

BASEDIR="/var/www/html/virtualclass"

java -jar /var/www/html/compiler/compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS  --language_in=ES6 \
--js $BASEDIR/external/src/jquery-1.12.4.js \
--js $BASEDIR/external/src/jquery-ui.js \
--js $BASEDIR/external/src/handlebars-v4.0.8.js \
--js $BASEDIR/external/src/mo_slickQuiz.js \
--js $BASEDIR/external/src/poll-d3.js \
--js $BASEDIR/external/src/poll-c3.js \
--js $BASEDIR/external/src/video.js \
--js $BASEDIR/external/src/youtube.js \
--js $BASEDIR/external/src/videojs-contrib-hls.js \
--js $BASEDIR/external/src/s3.fine-uploader.js \
--js $BASEDIR/external/src/bootstrap-3.3.7.js \
--js $BASEDIR/external/src/pdf.js \
--js $BASEDIR/external/src/codemirror.js \
--js $BASEDIR/external/src/codemirror-continuelist.js \
--js $BASEDIR/external/src/codemirror-xml.js \
--js $BASEDIR/external/src/codemirror-markdown.js \
--create_source_map $BASEDIR/build/src/external-min \
--js_output_file $BASEDIR/build/src/external.min.js

